In [3]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

<h1>For Dataset1<h1/>

In [16]:
dataset=pd.read_excel('Dataset1.xlsx')
dataset

     Cheese  Butter  Bread  Chicken    Oil    Jam
0      True    True  False     True   True   True
1      True   False  False    False  False  False
2      True    True  False     True  False   True
3     False    True   True     True  False  False
4      True    True  False    False   True   True
..      ...     ...    ...      ...    ...    ...
494    True   False  False     True   True  False
495    True    True   True     True   True  False
496   False   False   True    False  False   True
497    True   False  False    False   True  False
498    True    True   True     True  False   True

[499 rows x 6 columns]

In [23]:
from mlxtend.frequent_patterns import apriori

frequent_itemset= apriori(dataset,min_support=0.1,use_colnames=True)
frequent_itemset

     support                   itemsets
0   0.533066                   (Cheese)
1   0.488978                   (Butter)
2   0.501002                    (Bread)
3   0.492986                  (Chicken)
4   0.470942                      (Oil)
5   0.507014                      (Jam)
6   0.250501           (Cheese, Butter)
7   0.264529            (Cheese, Bread)
8   0.266533          (Cheese, Chicken)
9   0.232465              (Cheese, Oil)
10  0.260521              (Jam, Cheese)
11  0.242485            (Bread, Butter)
12  0.260521          (Chicken, Butter)
13  0.252505              (Oil, Butter)
14  0.264529              (Jam, Butter)
15  0.246493           (Chicken, Bread)
16  0.234469               (Oil, Bread)
17  0.250501               (Jam, Bread)
18  0.238477             (Chicken, Oil)
19  0.266533             (Jam, Chicken)
20  0.228457                 (Jam, Oil)
21  0.122244    (Cheese, Bread, Butter)
22  0.136273  (Cheese, Chicken, Butter)
23  0.122244      (Cheese, Oil, Butter)
24  0.132265      (Jam, Cheese, Butter)
25  0.136273   (Cheese, Chicken, Bread)
26  0.108216       (Cheese, Oil, Bread)
27  0.132265       (Jam, Cheese, Bread)
28  0.124248     (Cheese, Chicken, Oil)
29  0.138277     (Jam, Cheese, Chicken)
30  0.102204         (Jam, Cheese, Oil)
31  0.128257   (Chicken, Bread, Butter)
32  0.118236       (Oil, Bread, Butter)
33  0.126253       (Jam, Bread, Butter)
34  0.138277     (Chicken, Oil, Butter)
35  0.146293     (Jam, Chicken, Butter)
36  0.132265         (Jam, Oil, Butter)
37  0.122244      (Oil, Chicken, Bread)
38  0.132265      (Jam, Chicken, Bread)
39  0.116232          (Jam, Oil, Bread)
40  0.126253        (Jam, Chicken, Oil)

In [26]:
from mlxtend.frequent_patterns import association_rules
result=association_rules(frequent_itemset,metric="confidence",min_threshold=0.3)
#Print Final Rules
result

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Cheese),(Butter),0.533066,0.488978,0.250501,0.469925,0.961035,-0.010157,0.964056
1,(Butter),(Cheese),0.488978,0.533066,0.250501,0.512295,0.961035,-0.010157,0.957411
2,(Cheese),(Bread),0.533066,0.501002,0.264529,0.496241,0.990496,-0.002538,0.990548
3,(Bread),(Cheese),0.501002,0.533066,0.264529,0.528000,0.990496,-0.002538,0.989267
4,(Cheese),(Chicken),0.533066,0.492986,0.266533,0.500000,1.014228,0.003739,1.014028
...,...,...,...,...,...,...,...,...,...
85,"(Jam, Bread)",(Oil),0.250501,0.470942,0.116232,0.464000,0.985260,-0.001739,0.987049
86,"(Oil, Bread)",(Jam),0.234469,0.507014,0.116232,0.495726,0.977737,-0.002647,0.977616
87,"(Jam, Chicken)",(Oil),0.266533,0.470942,0.126253,0.473684,1.005823,0.000731,1.005210
88,"(Jam, Oil)",(Chicken),0.228457,0.492986,0.126253,0.552632,1.120988,0.013626,1.133325
89,"(Chicken, Oil)",(Jam),0.238477,0.507014,0.126253,0.529412,1.044176,0.005341,1.047595

In [28]:
final_result=result[['antecedents','consequents','support','confidence','lift']]
final_result

       antecedents consequents   support  confidence      lift
0         (Cheese)    (Butter)  0.250501    0.469925  0.961035
1         (Butter)    (Cheese)  0.250501    0.512295  0.961035
2         (Cheese)     (Bread)  0.264529    0.496241  0.990496
3          (Bread)    (Cheese)  0.264529    0.528000  0.990496
4         (Cheese)   (Chicken)  0.266533    0.500000  1.014228
..             ...         ...       ...         ...       ...
85    (Jam, Bread)       (Oil)  0.116232    0.464000  0.985260
86    (Oil, Bread)       (Jam)  0.116232    0.495726  0.977737
87  (Jam, Chicken)       (Oil)  0.126253    0.473684  1.005823
88      (Jam, Oil)   (Chicken)  0.126253    0.552632  1.120988
89  (Chicken, Oil)       (Jam)  0.126253    0.529412  1.044176

[90 rows x 5 columns]

<h1>For Dataset2<h1/>

In [30]:
dataset2=pd.read_excel('Dataset2.xlsx')
dataset2

       Oil   salt   Ghee  Chilli Powder  Sugar  Pulses
0    False   True   True          False   True    True
1     True  False  False          False  False    True
2     True  False   True           True   True   False
3     True   True   True           True  False   False
4     True  False   True           True  False   False
..     ...    ...    ...            ...    ...     ...
794  False  False   True           True   True   False
795  False  False   True           True  False    True
796   True  False  False          False   True   False
797   True  False  False           True  False   False
798  False   True   True           True   True   False

[799 rows x 6 columns]

In [34]:
frequent_itemset2= apriori(dataset2,min_support=0.1,use_colnames=True)
frequent_itemset2

     support                        itemsets
0   0.468085                           (Oil)
1   0.493116                          (salt)
2   0.504380                          (Ghee)
3   0.505632                 (Chilli Powder)
4   0.511890                         (Sugar)
5   0.470588                        (Pulses)
6   0.230288                     (salt, Oil)
7   0.222778                     (Ghee, Oil)
8   0.236546            (Chilli Powder, Oil)
9   0.230288                    (Oil, Sugar)
10  0.225282                   (Oil, Pulses)
11  0.255319                    (salt, Ghee)
12  0.247810           (Chilli Powder, salt)
13  0.255319                   (salt, Sugar)
14  0.222778                  (salt, Pulses)
15  0.255319           (Chilli Powder, Ghee)
16  0.256571                   (Ghee, Sugar)
17  0.234043                  (Ghee, Pulses)
18  0.255319          (Chilli Powder, Sugar)
19  0.227785         (Chilli Powder, Pulses)
20  0.246558                 (Sugar, Pulses)
21  0.105131               (salt, Oil, Ghee)
22  0.116395      (Chilli Powder, salt, Oil)
23  0.121402              (salt, Oil, Sugar)
24  0.115144             (salt, Oil, Pulses)
25  0.106383      (Chilli Powder, Ghee, Oil)
26  0.111389              (Ghee, Oil, Sugar)
27  0.106383             (Ghee, Oil, Pulses)
28  0.116395     (Chilli Powder, Oil, Sugar)
29  0.113892    (Chilli Powder, Oil, Pulses)
30  0.111389            (Oil, Sugar, Pulses)
31  0.126408     (Chilli Powder, salt, Ghee)
32  0.125156             (salt, Sugar, Ghee)
33  0.120150            (Pulses, salt, Ghee)
34  0.125156    (Chilli Powder, salt, Sugar)
35  0.107635   (Chilli Powder, salt, Pulses)
36  0.117647           (salt, Sugar, Pulses)
37  0.123905    (Chilli Powder, Ghee, Sugar)
38  0.112641   (Chilli Powder, Ghee, Pulses)
39  0.127660           (Ghee, Sugar, Pulses)
40  0.115144  (Chilli Powder, Sugar, Pulses)

In [38]:
result2=association_rules(frequent_itemset2,metric="confidence",min_threshold=0.5)
#Print Final Rules
result2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(salt),(Oil),0.493116,0.468085,0.230288,0.467005,0.997693,-0.000533,0.997974
1,(Oil),(salt),0.468085,0.493116,0.230288,0.491979,0.997693,-0.000533,0.997760
2,(Ghee),(Oil),0.504380,0.468085,0.222778,0.441687,0.943605,-0.013315,0.952719
3,(Oil),(Ghee),0.468085,0.504380,0.222778,0.475936,0.943605,-0.013315,0.945723
4,(Chilli Powder),(Oil),0.505632,0.468085,0.236546,0.467822,0.999437,-0.000133,0.999505
...,...,...,...,...,...,...,...,...,...
85,"(Ghee, Pulses)",(Sugar),0.234043,0.511890,0.127660,0.545455,1.065570,0.007856,1.073842
86,"(Sugar, Pulses)",(Ghee),0.246558,0.504380,0.127660,0.517766,1.026540,0.003300,1.027758
87,"(Chilli Powder, Sugar)",(Pulses),0.255319,0.470588,0.115144,0.450980,0.958333,-0.005006,0.964286
88,"(Chilli Powder, Pulses)",(Sugar),0.227785,0.511890,0.115144,0.505495,0.987506,-0.001457,0.987067
89,"(Sugar, Pulses)",(Chilli Powder),0.246558,0.505632,0.115144,0.467005,0.923607,-0.009524,0.927528

In [36]:
final_result2=result2[['antecedents','consequents','support','confidence','lift']]
final_result2

                antecedents      consequents   support  confidence      lift
0                    (salt)            (Oil)  0.230288    0.467005  0.997693
1                     (Oil)           (salt)  0.230288    0.491979  0.997693
2                    (Ghee)            (Oil)  0.222778    0.441687  0.943605
3                     (Oil)           (Ghee)  0.222778    0.475936  0.943605
4           (Chilli Powder)            (Oil)  0.236546    0.467822  0.999437
..                      ...              ...       ...         ...       ...
85           (Ghee, Pulses)          (Sugar)  0.127660    0.545455  1.065570
86          (Sugar, Pulses)           (Ghee)  0.127660    0.517766  1.026540
87   (Chilli Powder, Sugar)         (Pulses)  0.115144    0.450980  0.958333
88  (Chilli Powder, Pulses)          (Sugar)  0.115144    0.505495  0.987506
89          (Sugar, Pulses)  (Chilli Powder)  0.115144    0.467005  0.923607

[90 rows x 5 columns]